{% set version = "4.4.1" %}
{% set version_major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: cmake-no-system
  version: {{ version }}

source:
  - url: https://github.com/Kitware/CMake/releases/download/v{{ version }}/cmake-{{ version }}.tar.gz
    sha256: 95d4721f3625fb0d9d6ca480dd59a46c84b4c157f7fadd2e9b179ef9c871174d
  - url: https://cmake.org/files/v{{ version_major_minor }}/cmake-{{ version }}-windows-x86_64.zip  # [win]
    sha256: 091919e1cde162b69d2d5e0f3b1f5670c973e72133f78126fbb18042947d6f19  # [win]
    folder: cmake-{{ version }}-windows  # [win]

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - make  # [unix]
    - ninja
  run_constrained:
    - cmake ==dev

test:
  commands:
    - cmake --version
    - ctest --version
    - cpack --version

about:
  home: http://www.cmake.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE.rst
    - Utilities/cmbzip2/LICENSE
    - Utilities/cmcppdap/LICENSE
    - Utilities/cmcurl/COPYING
    - Utilities/cmexpat/COPYING
    - Utilities/cmjsoncpp/LICENSE
    - Utilities/cmlibarchive/COPYING
    - Utilities/cmliblzma/COPYING
    - Utilities/cmlibrhash/COPYING
    - Utilities/cmlibuv/LICENSE
    - Utilities/cmzlib/Copyright.txt
    - Utilities/cmzstd/LICENSE
  summary: CMake built without system libraries for use when building CMake dependencies.

extra:
  recipe-maintainers:
    - jjhelmus
    - beckermr
    - xhochy
