{% set version = "4.3.0" %}
{% set version_major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: cmake-no-system
  version: {{ version }}

source:
  - url: https://github.com/Kitware/CMake/releases/download/v{{ version }}/cmake-{{ version }}.tar.gz
    sha256: f51b3c729f85d8dde46a92c071d2826ea6afb77d850f46894125de7cc51baa77
  - url: https://cmake.org/files/v{{ version_major_minor }}/cmake-{{ version }}-windows-x86_64.zip  # [win]
    sha256: 0f664f44eeb5b35b77f83e0984459c0dfa70539bd215c54ae1059604fd4f77ea  # [win]
    folder: cmake-{{ version }}-windows  # [win]

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - make  # [unix]
    - ninja
  run_constrained:
    - cmake ==dev

test:
  commands:
    - cmake --version
    - ctest --version
    - cpack --version

about:
  home: http://www.cmake.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE.rst
    - Utilities/cmbzip2/LICENSE
    - Utilities/cmcppdap/LICENSE
    - Utilities/cmcurl/COPYING
    - Utilities/cmexpat/COPYING
    - Utilities/cmjsoncpp/LICENSE
    - Utilities/cmlibarchive/COPYING
    - Utilities/cmliblzma/COPYING
    - Utilities/cmlibrhash/COPYING
    - Utilities/cmlibuv/LICENSE
    - Utilities/cmzlib/Copyright.txt
    - Utilities/cmzstd/LICENSE
  summary: CMake built without system libraries for use when building CMake dependencies.

extra:
  recipe-maintainers:
    - jjhelmus
    - beckermr
    - xhochy
